In [1]:
import pandas as pd
import nltk
import re

In [2]:
df =pd.read_csv("medicine_reviews.csv")

In [3]:
df.head()

                                              review     label
0  Depression: "I have taken anti-depressants for...  positive
1  Pain: "I am 30 years old. I had a multiple com...  positive
2  Pain: "I love my Butrans patch!!! And it has r...  positive
3  Depression: "This medicine saved my life. I wa...  positive
4  Anxiety: "I have been suffering with this anxi...  positive

In [4]:
df.shape

(12112, 2)

## preprocessing

In [5]:
text = df['review'][0]
text

'Depression: "I have taken anti-depressants for years, with some improvement but mostly moderate to severe side affects, which makes me go off them.\r\n\r\nI only take Cymbalta now mostly for pain.\r\n\r\nWhen I began Deplin, I noticed a major improvement overnight. More energy, better disposition, and no sinking to the low lows of major depression. I have been taking it for about 3 months now and feel like a normal person for the first time ever. Best thing, no side effects."'

In [6]:
text = text.lower() # lowercase
text

'depression: "i have taken anti-depressants for years, with some improvement but mostly moderate to severe side affects, which makes me go off them.\r\n\r\ni only take cymbalta now mostly for pain.\r\n\r\nwhen i began deplin, i noticed a major improvement overnight. more energy, better disposition, and no sinking to the low lows of major depression. i have been taking it for about 3 months now and feel like a normal person for the first time ever. best thing, no side effects."'

In [7]:
text = re.sub(r'[^a-z\s]','',text) # removed puntucation, numbers
text

'depression i have taken antidepressants for years with some improvement but mostly moderate to severe side affects which makes me go off them\r\n\r\ni only take cymbalta now mostly for pain\r\n\r\nwhen i began deplin i noticed a major improvement overnight more energy better disposition and no sinking to the low lows of major depression i have been taking it for about  months now and feel like a normal person for the first time ever best thing no side effects'

In [8]:
print(text)

depression i have taken antidepressants for years with some improvement but mostly moderate to severe side affects which makes me go off them

i only take cymbalta now mostly for pain

when i began deplin i noticed a major improvement overnight more energy better disposition and no sinking to the low lows of major depression i have been taking it for about  months now and feel like a normal person for the first time ever best thing no side effects

In [9]:
sample_text = "Hello!!!... Arun 123"
re.sub(r'[^A-Za-z\s]',"",sample_text)

'Hello Arun '

In [10]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [11]:
# tokenization
from nltk.tokenize import word_tokenize
tokens = word_tokenize(text)
print(tokens)

['depression', 'i', 'have', 'taken', 'antidepressants', 'for', 'years', 'with', 'some', 'improvement', 'but', 'mostly', 'moderate', 'to', 'severe', 'side', 'affects', 'which', 'makes', 'me', 'go', 'off', 'them', 'i', 'only', 'take', 'cymbalta', 'now', 'mostly', 'for', 'pain', 'when', 'i', 'began', 'deplin', 'i', 'noticed', 'a', 'major', 'improvement', 'overnight', 'more', 'energy', 'better', 'disposition', 'and', 'no', 'sinking', 'to', 'the', 'low', 'lows', 'of', 'major', 'depression', 'i', 'have', 'been', 'taking', 'it', 'for', 'about', 'months', 'now', 'and', 'feel', 'like', 'a', 'normal', 'person', 'for', 'the', 'first', 'time', 'ever', 'best', 'thing', 'no', 'side', 'effects']

In [12]:
len(tokens)

80

In [13]:
# stopwords

nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [14]:
from nltk.corpus import stopwords
stop_words = stopwords.words('english')
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [15]:
filtered_tokens = []
for word in tokens:
  if word not in stop_words:
    filtered_tokens.append(word)
print(filtered_tokens)

['depression', 'taken', 'antidepressants', 'years', 'improvement', 'mostly', 'moderate', 'severe', 'side', 'affects', 'makes', 'go', 'take', 'cymbalta', 'mostly', 'pain', 'began', 'deplin', 'noticed', 'major', 'improvement', 'overnight', 'energy', 'better', 'disposition', 'sinking', 'low', 'lows', 'major', 'depression', 'taking', 'months', 'feel', 'like', 'normal', 'person', 'first', 'time', 'ever', 'best', 'thing', 'side', 'effects']

In [16]:
len(filtered_tokens)

43

In [17]:
# stemming
from nltk.stem import PorterStemmer
stemmer = PorterStemmer()

stemmed_tokens=[]
for word in filtered_tokens:
  stemmed_tokens.append(stemmer.stem(word))

print(stemmed_tokens)

['depress', 'taken', 'antidepress', 'year', 'improv', 'mostli', 'moder', 'sever', 'side', 'affect', 'make', 'go', 'take', 'cymbalta', 'mostli', 'pain', 'began', 'deplin', 'notic', 'major', 'improv', 'overnight', 'energi', 'better', 'disposit', 'sink', 'low', 'low', 'major', 'depress', 'take', 'month', 'feel', 'like', 'normal', 'person', 'first', 'time', 'ever', 'best', 'thing', 'side', 'effect']

In [18]:
stemmer.stem("mostly")

'mostli'

In [19]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [20]:
# lemmitization
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

lemmatized_tokens = []
for word in filtered_tokens:
  lemmatized_tokens.append(lemmatizer.lemmatize(word))

print(lemmatized_tokens)

['depression', 'taken', 'antidepressant', 'year', 'improvement', 'mostly', 'moderate', 'severe', 'side', 'affect', 'make', 'go', 'take', 'cymbalta', 'mostly', 'pain', 'began', 'deplin', 'noticed', 'major', 'improvement', 'overnight', 'energy', 'better', 'disposition', 'sinking', 'low', 'low', 'major', 'depression', 'taking', 'month', 'feel', 'like', 'normal', 'person', 'first', 'time', 'ever', 'best', 'thing', 'side', 'effect']

In [21]:
lemmatizer.lemmatize("mostly")

'mostly'

In [22]:
df['review'][0]

'Depression: "I have taken anti-depressants for years, with some improvement but mostly moderate to severe side affects, which makes me go off them.\r\n\r\nI only take Cymbalta now mostly for pain.\r\n\r\nWhen I began Deplin, I noticed a major improvement overnight. More energy, better disposition, and no sinking to the low lows of major depression. I have been taking it for about 3 months now and feel like a normal person for the first time ever. Best thing, no side effects."'

In [23]:
' '.join(lemmatized_tokens)

'depression taken antidepressant year improvement mostly moderate severe side affect make go take cymbalta mostly pain began deplin noticed major improvement overnight energy better disposition sinking low low major depression taking month feel like normal person first time ever best thing side effect'

In [24]:
# write a function(arg) --- pandas. apply(function)
# lower --> remove special characters --> Tokenization --> remove stopwords --> stemming/Lemmaitization -- > join the sentence

In [25]:
def preprocess_text(text,stem=False):
  text = text.lower()
  text = re.sub(r'[^a-z\s]','',text)
  tokens = word_tokenize(text)
  filtered_tokens = []
  for word in tokens:
    if word not in stop_words:
      filtered_tokens.append(word)
  if stem == True:
    stemmed_tokens = []
    for word in filtered_tokens:
      stemmed_tokens.append(stemmer.stem(word))
    return ' '.join(stemmed_tokens)
  else:
    lemmatized_tokens = []
    for word in filtered_tokens:
      lemmatized_tokens.append(lemmatizer.lemmatize(word))
    return ' '.join(lemmatized_tokens)


df['clean_review'] = df['review'].apply(preprocess_text)

# save this data as a new file , .csv

In [26]:
df.head()

,review,label,clean_review
0,"Depression: ""I have taken anti-depressants for...",positive,depression taken antidepressant year improveme...
1,"Pain: ""I am 30 years old. I had a multiple com...",positive,pain year old multiple composite spinal injury...
2,"Pain: ""I love my Butrans patch!!! And it has r...",positive,pain love butrans patch relieved half pain kno...
3,"Depression: ""This medicine saved my life. I wa...",positive,depression medicine saved life wit end antidep...
4,"Anxiety: ""I have been suffering with this anxi...",positive,anxiety suffering anxiety problem year startin...

In [27]:
df['label'] = df['label'].map({'positive':1,'negative':0})

In [28]:
df.head()

,review,label,clean_review
0,"Depression: ""I have taken anti-depressants for...",1,depression taken antidepressant year improveme...
1,"Pain: ""I am 30 years old. I had a multiple com...",1,pain year old multiple composite spinal injury...
2,"Pain: ""I love my Butrans patch!!! And it has r...",1,pain love butrans patch relieved half pain kno...
3,"Depression: ""This medicine saved my life. I wa...",1,depression medicine saved life wit end antidep...
4,"Anxiety: ""I have been suffering with this anxi...",1,anxiety suffering anxiety problem year startin...

In [29]:
df.shape

(12112, 3)

In [30]:
X = df['clean_review']
y= df['label']

In [31]:
from sklearn.feature_extraction.text import CountVectorizer # bow
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [32]:
# bag of words

vectorizer = CountVectorizer()
X_vectorizer = vectorizer.fit_transform(X)

In [33]:
X_vectorizer.shape

(12112, 13097)

In [34]:
vectorizer.get_feature_names_out()

array(['aa', 'aampe', 'aarp', ..., 'zyprexai', 'zyprexia', 'zzzquil'],
      dtype=object)

In [35]:
X_train,X_test,y_train,y_test = train_test_split(X_vectorizer,y,test_size=0.2,random_state=42)

In [36]:
model = RandomForestClassifier()

model.fit(X_train,y_train)

# prediction

y_pred = model.predict(X_test)

# accuracy
accuracy_score(y_test,y_pred)

0.9389186958316137

In [37]:
# training accuarcy

y_pred_train = model.predict(X_train)
accuracy_score(y_train,y_pred_train)

0.9995871606976984

In [38]:
new_review = ["This medicine caused severe headache"]
# new_review = ["This medicine is really good"]

# preprocess
# clean_reviewed =[]
# for review in new_review:
#   review = preprocess_text(review)
#   clean_reviewed.append(review)

clean_review = [preprocess_text(review) for review in new_review]

# convert into BoW vector
vector_input = vectorizer.transform(clean_review)

# prediction
prediction = model.predict(vector_input)

if prediction[0] ==1:
  print(f"The Review is Postive")
else:
  print(f"The Review is Negative")

The Review is Negative

In [39]:
prediction[0]

np.int64(0)

### TF-IDF

In [40]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
X_vectorizer = vectorizer.fit_transform(X)
print(X_vectorizer.shape)

(12112, 13097)

In [41]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X_vectorizer,y,test_size=0.2,random_state=42)

In [42]:
model = RandomForestClassifier()
model.fit(X_train,y_train)
# prediction
y_pred = model.predict(X_test)
# accuracy
accuracy_score(y_test,y_pred)

0.9401568303755675

In [43]:
# training accuarcy
y_pred_train = model.predict(X_train)
accuracy_score(y_train,y_pred_train)

0.9995871606976984

In [44]:
new_review = ["This medicine caused severe headache"]
new_review = ["This medicine is really good"]

# preprocess
# clean_reviewed =[]
# for review in new_review:
#   review = preprocess_text(review)
#   clean_reviewed.append(review)

clean_review = [preprocess_text(review) for review in new_review]

# convert into BoW vector
vector_input = vectorizer.transform(clean_review)

# prediction
prediction = model.predict(vector_input)

if prediction[0] ==1:
  print(f"The Review is Postive")
else:
  print(f"The Review is Negative")

The Review is Postive

## Word2vec

In [45]:
def preprocess_text_word2vec(text):
  text = text.lower()
  text = re.sub(r'[^a-z\s]','',text)
  tokens = word_tokenize(text)
  filtered_tokens = []
  for word in tokens:
    if word not in stop_words:
      filtered_tokens.append(word)
  lemmatized_tokens = []
  for word in filtered_tokens:
    lemmatized_tokens.append(lemmatizer.lemmatize(word))
  return lemmatized_tokens


df['token'] = df['review'].apply(preprocess_text_word2vec)

In [46]:
df.head()

,review,label,clean_review,token
0,"Depression: ""I have taken anti-depressants for...",1,depression taken antidepressant year improveme...,"[depression, taken, antidepressant, year, impr..."
1,"Pain: ""I am 30 years old. I had a multiple com...",1,pain year old multiple composite spinal injury...,"[pain, year, old, multiple, composite, spinal,..."
2,"Pain: ""I love my Butrans patch!!! And it has r...",1,pain love butrans patch relieved half pain kno...,"[pain, love, butrans, patch, relieved, half, p..."
3,"Depression: ""This medicine saved my life. I wa...",1,depression medicine saved life wit end antidep...,"[depression, medicine, saved, life, wit, end, ..."
4,"Anxiety: ""I have been suffering with this anxi...",1,anxiety suffering anxiety problem year startin...,"[anxiety, suffering, anxiety, problem, year, s..."

In [47]:
! pip install gensim

Collecting gensim
  Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.6.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.2.1)
Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 66.0 MB/s eta 0:00:00
Installing collected packages: gensim
Successfully installed gensim-4.4.0

In [48]:
df['token'].tolist()

[['depression',
  'taken',
  'antidepressant',
  'year',
  'improvement',
  'mostly',
  'moderate',
  'severe',
  'side',
  'affect',
  'make',
  'go',
  'take',
  'cymbalta',
  'mostly',
  'pain',
  'began',
  'deplin',
  'noticed',
  'major',
  'improvement',
  'overnight',
  'energy',
  'better',
  'disposition',
  'sinking',
  'low',
  'low',
  'major',
  'depression',
  'taking',
  'month',
  'feel',
  'like',
  'normal',
  'person',
  'first',
  'time',
  'ever',
  'best',
  'thing',
  'side',
  'effect'],
 ['pain',
  'year',
  'old',
  'multiple',
  'composite',
  'spinal',
  'injury',
  'year',
  'ago',
  'ache',
  'pain',
  'unbearable',
  'started',
  'taking',
  'antiinflammatories',
  'year',
  'ago',
  'started',
  'getting',
  'injection',
  'every',
  'month',
  'toradol',
  'quotdepoquot',
  'something',
  'almost',
  'pain',
  'med',
  'mean',
  'still',
  'bad',
  'day',
  'function'],
 ['pain',
  'love',
  'butrans',
  'patch',
  'relieved',
  'half',
  'pain',
  'know',
  'take',
  'less',
  'half',
  'pain',
  'killer',
  'patch',
  'change',
  'patch',
  'every',
  'saturday',
  'miss',
  'hour',
  'pain',
  'start',
  'reside',
  'heavy',
  'drinker',
  'would',
  'advise',
  'trying',
  'patch'],
 ['depression',
  'medicine',
  'saved',
  'life',
  'wit',
  'end',
  'antidepressant',
  'ready',
  'give',
  'doctor',
  'finally',
  'prescribed',
  'many',
  'failed',
  'medication',
  'glad',
  'honestly',
  'know',
  'would',
  'without',
  'effexor',
  'xr',
  'side',
  'effect',
  'mild',
  'compared',
  'antidepressant',
  'tried',
  'drowsy',
  'first',
  'couple',
  'day',
  'tolerable',
  'highly',
  'recommend',
  'severe',
  'depression',
  'would',
  'also',
  'like',
  'mention',
  'people',
  'realize',
  'light',
  'end',
  'tunnel',
  'get',
  'better',
  'never',
  'give'],
 ['anxiety',
  'suffering',
  'anxiety',
  'problem',
  'year',
  'starting',
  'interfere',
  'life',
  'confident',
  'person',
  'socially',
  'fear',
  'presentation',
  'huge',
  'would',
  'voice',
  'would',
  'tremble',
  'extent',
  'sounded',
  'like',
  'full',
  'cry',
  'researched',
  'medication',
  'fear',
  'found',
  'propanolol',
  'doctor',
  'prescribed',
  'mg',
  'half',
  'inderal',
  'propanolol',
  'despite',
  'say',
  'hesitant',
  'giving',
  'prescription',
  'said',
  'regularly',
  'give',
  'musicianspublic',
  'speaker',
  'etc',
  'worked',
  'wonder',
  'longer',
  'embarrass',
  'self',
  'feel',
  'happy',
  'confident',
  'may',
  'still',
  'feel',
  'nervy',
  'adrenaline',
  'kick',
  'suffered',
  'symptom',
  'take',
  'seldomly'],
 ['depression',
  'medication',
  'amazing',
  'day',
  'extremely',
  'sick',
  'started',
  'feel',
  'amazing',
  'month',
  'happy',
  'time',
  'depressive',
  'thought',
  'kind',
  'block',
  'sad',
  'thought',
  'work',
  'perfectly'],
 ['depression',
  'genius',
  'psychiatrist',
  'started',
  'drug',
  'fall',
  'first',
  'week',
  'felt',
  'even',
  'worse',
  'started',
  'taking',
  'fluoxetine',
  'many',
  'month',
  'drug',
  'eventually',
  'taking',
  'mg',
  'day',
  'manic',
  'thought',
  'amp',
  'episode',
  'psychiatrist',
  'decided',
  'bipolar',
  'started',
  'seroquel',
  'rather',
  'give',
  'break',
  'nervous',
  'system',
  'readjust',
  'natural',
  'state',
  'also',
  'ended',
  'taking',
  'month',
  'dose',
  'retrospect',
  'wish',
  'hadnt',
  'taken',
  'either',
  'fluoxetineprozac',
  'seroquelquetiapine'],
 ['pain',
  'open',
  'heart',
  'surgery',
  'double',
  'mastectomy',
  'span',
  'year',
  'painful',
  'nerve',
  'pain',
  'time',
  'bio',
  'freeze',
  'roll',
  'definitely',
  'work',
  'pain',
  'unfortunately',
  'literally',
  'burned',
  'chest',
  'dont',
  'want',
  'anyone',
  'go',
  'thisthank',
  'well',
  'everyone'],
 ['depression',
  'f',
  'wellbutrin',
  'sr',
  'mg',
  'twice',
  'day',
  'amp',
  'feel',
  'much',
  'better',
  'ive',
  'tried',
  'many',
  'different',
  'sssnris',
  'past',
  'year',
  'amp',
  'made',
  'extreme',
  'suicidal',
  'thought',
  'kind',
  'given',
  'hope',
  'finding',
  'something',
  'worked',
  'new',
  'psychiatrist',
  'recommended',
  'trying',
  'wellbutrin',
  'first',
  'week',
  'rough',
  'blurry',
  'vision',
  'shake',
  'amp',
  'extreme',
  'light',
  'sensitivity',
  'negative',
  'side',
  'effect',
  'went',
  'away',
  'week',
  'im',
  'month',
  'amp',
  'mood',
  'significantly',
  'increased',
  'amazing',
  'depression',
  'worsens',
  'significantly',
  'winter',
  'feel',
  'optimistic',
  'future',
  'sex',
  'drive',
  'better',
  'energy',
  'amp',
  'focused',
  'fibromyalgia',
  'well',
  'huge',
  'ive',
  'quit',
  'smoking'],
 ['anxiety',
  'changed',
  'life',
  'completely',
  'actually',
  'function',
  'social',
  'setting'],
 ['depression',
  'severe',
  'depression',
  'since',
  'teen',
  'antidepressant',
  'many',
  'year',
  'fortunately',
  'beneficial',
  'effect',
  'several',
  'year',
  'effective',
  'treatment',
  'date',
  'combination',
  'wellbutrin',
  'cymbalta',
  'took',
  'combination',
  'ten',
  'year',
  'unfortunately',
  'recently',
  'started',
  'slipping',
  'downward',
  'increased',
  'depression',
  'feeling',
  'control',
  'prescribed',
  'fetzima',
  'transitioned',
  'cymbalta',
  'completed',
  'starter',
  'pack',
  'benefit',
  'increased',
  'energy',
  'dr',
  'increased',
  'doseage',
  'mg',
  'mg',
  'two',
  'week',
  'never',
  'felt',
  'lack',
  'better',
  'word',
  'crazy',
  'life',
  'irretiable',
  'angry',
  'depressed',
  'unreasonable',
  'feeling'],
 ['anxiety',
  'day',
  'taking',
  'major',
  'anxiety',
  'slight',
  'depression',
  'mg',
  'daily',
  'anxiety',
  'lifting',
  'feel',
  'much',
  'control',
  'calm',
  'side',
  'symptom',
  'slight',
  'wheezy',
  'tired',
  'feeling',
  'took',
  'last',
  'night',
  'pm',
  'asleep',
  'pm',
  'first',
  'time',
  'year',
  'fell',
  'asleep',
  'without',
  'racing',
  'thought',
  'worry'],
 ['pain',
  'worked',
  'great',
  'back',
  'pain',
  'nonnarcotic',
  'dont',
  'feel',
  'woozy'],
 ['pain',
  'love',
  'celebrex',
  'degenerative',
  'disk',
  'disease',
  'bulged',
  'disk',
  'degenerative',
  'hip',
  'doctor',
  'try',
  'learning',
  'tolerate',
  'ibupropen',
  'day',
  'better',
  'far',
  'daily',
  'pain',
  'thing',
  'exercise',
  'could',
  'due',
  'pain',
  'take',
  'homeopathic',
  'anti',
  'inflammatory',
  'supplement',
  'well',
  'year',
  'old',
  'photographer',
  'pilate',
  'student',
  'teacher',
  'living',
  'pain',
  'year',
  'wonderful',
  'relief'],
 ['anxiety',
  'prescribed',
  'via',
  'psychiatrist',
  'severe',
  'panic',
  'attack',
  'year',
  'take',
  'dosage',
  'late',
  'forget',
  'take',
  'withdrawal',
  'symptom',
  'kick',
  'gnawing',
  'physical',
  'pain',
  'breathlessness',
  'disorientation',
  'time',
  'difficulty',
  'word',
  'finding',
  'speaking',
  'severe',
  'muscle',
  'pain',
  'stiffness',
  'nausea',
  'labile',
  'emotion',
  'panic'],
 ['anxiety',
  'suffered',
  'anxiety',
  'depression',
  'month',
  'side',
  'effect',
  'took',
  'citalopram',
  'prozac',
  'worsened',
  'side',
  'effect',
  'finally',
  'doctor',
  'gave',
  'mirtazapine',
  'almost',
  'overnight',
  'seemed',
  'improve',
  'first',
  'full',
  'sleep',
  'month',
  'felt',
  'like',
  'eating',
  'slowly',
  'course',
  'week',
  'side',
  'effect',
  'left',
  'within',
  'week',
  'less',
  'medicine',
  'month',
  'later',
  'lead',
  'old',
  'life',
  'suffer',
  'sleep',
  'lost',
  'appetite',
  'due',
  'anxiety',
  'give',
  'go',
  'good',
  'luck'],
 ['anxiety',
  'ive',
  'tormented',
  'anxiety',
  'since',
  'childhood',
  'year',
  'old',
  'lot',
  'life',
  'ive',
  'diagnosed',
  'depression',
  'bipolar',
  'disorder',
  'anxiety',
  'panic',
  'attack',
  'add',
  'ive',
  'medicated',
  'life',
  'well',
  'anxiety',
  'got',
  'bad',
  'high',
  'school',
  'home',
  'schooled',
  'wake',
  'morning',
  'feeling',
  'like',
  'heart',
  'explode',
  'apparent',
  'reason',
  'get',
  'intense',
  'irrational',
  'fear',
  'intense',
  'impulse',
  'harm',
  'cant',
  'take',
  'get',
  'frustrated',
  'start',
  'throwing',
  'breaking',
  'thing',
  'cant',
  'stand',
  'alone',
  'lot',
  'time',
  'xanax',
  'work',
  'fast',
  'calm',
  'without',
  'knocking',
  'depending',
  'severity',
  'attack',
  'take',
  'mg',
  'less',
  'mg'],
 ['depression', 'worked', 'week', 'stopped'],
 ['depression',
  'medication',
  'brilliant',
  'completely',
  'got',
  'rid',
  'depression',
  'social',
  'phobia',
  'take',
  'mgday',
  'ssri',
  'didnt',
  'really',
  'work',
  'laying',
  'bed',
  'day',
  'thinking',
  'suicide',
  'death',
  'started',
  'nardil',
  'life',
  'completely',
  'changed',
  'thank',
  'goodness',
  'medication'],
 ['depression',
  'bad',
  'one',
  'point',
  'anxieyy',
  'depression',
  'ocd',
  'working',
  'together',
  'horrible',
  'disgusting',
  'thought',
  'ocd',
  'driving',
  'constant',
  'panic',
  'attack',
  'anxiety',
  'roof',
  'drove',
  'stay',
  'door',
  'avoid',
  'trigger',
  'pushed',
  'deep',
  'deep',
  'depression',
  'ive',
  'zoloft',
  'month',
  'low',
  'dose',
  'mg',
  'feel',
  'much',
  'better',
  'able',
  'go',
  'get',
  'job',
  'excelling',
  'got',
  'three',
  'raise',
  'month',
  'felt',
  'bit',
  'anxiety',
  'ocd',
  'poking',
  'may',
  'need',
  'raise',
  'dose',
  'med',
  'changed',
  'life',
  'far',
  'rut',
  'dont',
  'give',
  'regain',
  'life',
  'back'],
 ['anxiety',
  'medicine',
  'extremely',
  'horrible',
  'experience',
  'doctor',
  'prescribed',
  'anxiety',
  'day',
  'one',
  'sent',
  'edge',
  'felt',
  'anxiety',
  'attack',
  'medication',
  'made',
  'feel',
  'fifty',
  'time',
  'worse',
  'felt',
  'like',
  'drank',
  'million',
  'milligram',
  'coffee',
  'pin',
  'needle',
  'hour',
  'reading',
  'review',
  'hate',
  'didnt',
  'affect',
  'majority',
  'hate',
  'anxiety',
  'cant',
  'see',
  'taking',
  'another',
  'one',
  'pill',
  'ever'],
 ['depression',
  'take',
  'trazodone',
  'help',
  'balance',
  'effect',
  'cymbalta',
  'sleep',
  'help',
  'depression',
  'experience',
  'wonderful',
  'help',
  'fall',
  'asleep',
  'sleep',
  'restfully',
  'together',
  'cymbalta',
  'trazodone',
  'completely',
  'eradicated',
  'depression'],
 ['anxiety',
  'taken',
  'medicine',
  'year',
  'gained',
  'lot',
  'weight',
  'weight',
  'watcher',
  'diet',
  'lost',
  'lb',
  'far',
  'happy',
  'mg',
  'bad',
  'restless',
  'leg',
  'reduced',
  'mg',
  'sleep',
  'great',
  'hour',
  'intolerable',
  'insomnia',
  'entire',
  'life',
  'wonder',
  'would',
  'happen',
  'reduced',
  'mg',
  'also',
  'added',
  'mg',
  'prozac',
  'daytime',
  'energy',
  'work',
  'great'],
 ['pain',
  'also',
  'knee',
  'pain',
  'shoulder',
  'pain',
  'elbow',
  'hand',
  'finger',
  'pain',
  'norco',
  'seems',
  'work',
  'best',
  'knee',
  'pain'],
 ['depression',
  'methylphenidate',
  'changed',
  'life',
  'depression',
  'almost',
  'nonexistent',
  'also',
  'stopped',
  'dwelling',
  'problem',
  'take',
  'mg',
  'methylphenidate',
  'xr',
  'along',
  'mg',
  'effexor',
  'xr'],
 ['depression',
  'yearold',
  'female',
  'ive',
  'always',
  'melancholic',
  'person',
  'given',
  'family',
  'history',
  'anxiety',
  'anger',
  'issue',
  'younger',
  'able',
  'experience',
  'happiness',
  'got',
  'older',
  'two',
  'kid',
  'got',
  'worse',
  'would',
  'get',
  'angry',
  'sad',
  'drop',
  'hat',
  'would',
  'sink',
  'depression',
  'also',
  'became',
  'difficult',
  'manage',
  'stress',
  'anxiety',
  'began',
  'seeing',
  'therapist',
  'suggested',
  'get',
  'physical',
  'primary',
  'care',
  'physician',
  'ask',
  'get',
  'prescription',
  'antidepressant',
  'put',
  'mg',
  'lexapro',
  'first',
  'day',
  'lightheaded',
  'groggy',
  'aware',
  'every',
  'sensation',
  'body',
  'also',
  'thirsty',
  'week',
  'felt',
  'benefit',
  'feel',
  'happy'],
 ['anxiety',
  'self',
  'medicating',
  'year',
  'tramadol',
  'suffer',
  'anxiety',
  'panic',
  'attack',
  'depression',
  'taking',
  'way',
  'much',
  'tramadol',
  'cope',
  'life',
  'spending',
  'money',
  'didnt',
  'buy',
  'miracle',
  'drug',
  'work',
  'great',
  'point',
  'sleep',
  'dodge',
  'thing',
  'social',
  'im',
  'day',
  'already',
  'feel',
  'pre',
  'depression',
  'returning',
  'oh',
  'also',
  'take',
  'vistaril',
  'panic',
  'anxiery',
  'really',
  'hit',
  'ive',
  'taken',
  'mg',
  'lexapro',
  'one',
  'mg',
  'vistiral',
  'morning',
  'feel',
  'great',
  'doesnt',
  'give',
  'euphoric',
  'feeling',
  'tram',
  'much',
  'better',
  'almost',
  'feel',
  'normal',
  'feel',
  'great',
  'already',
  'imagine',
  'much',
  'better',
  'itll',
  'get'],
 ['anxiety',
  'many',
  'people',
  'unreasonably',
  'scared',
  'klonopins',
  'bad',
  'withdrawal',
  'drama',
  'well',
  'true',
  'painful',
  'process',
  'get',
  'away',
  'klonopin',
  'stepped',
  'comfortable',
  'zone',
  'want',
  'say',
  'would',
  'rather',
  'feel',
  'relaxed',
  'comfortable',
  'struggling',
  'unnecessary',
  'anxiety',
  'caused',
  'neurotransmitter',
  'unbalance',
  'medication',
  'truly',
  'gave',
  'freedom',
  'fear',
  'agitation',
  'get',
  'back',
  'life'],
 ['depression',
  'took',
  'pristiq',
  'month',
  'one',
  'pill',
  'day',
  'im',
  'currently',
  'tapering',
  'caused',
  'following',
  'effect',
  'loss',
  'emotion',
  'uncontrolable',
  'shaking',
  'inability',
  'feel',
  'hungry',
  'full',
  'amp',
  'inability',
  'feel',
  'pain',
  'im',
  'anti',
  'depressant',
  'gp',
  'thought',
  'good',
  'idea',
  'prescribe',
  'dont',
  'think',
  'ill',
  'ever',
  'take',
  'another',
  'anti',
  'depressant',
  'id',
  'rather',
  'feel',
  'everything',
  'nothing'],
 ['pain',
  'medicine',
  'joke',
  'want',
  'take',
  'percocet',
  'hydrocodone',
  'put',
  'medicine',
  'supposed',
  'longer',
  'acting',
  'irsquod',
  'rather',
  'take',
  'six',
  'percocet',
  'mg',
  'day',
  'one',
  'mg',
  'four',
  'week',
  'didnrsquot',
  'help',
  'pain',
  'whatsoever'],
 ['depression',
  'taking',
  'zoloft',
  'year',
  'take',
  'mg',
  'daily',
  'found',
  'symptom',
  'diminished',
  'time',
  'real',
  'stress',
  'take',
  'extra',
  'pill',
  'say',
  'none',
  'previous',
  'drug',
  'took',
  'helped',
  'depression',
  'post',
  'traumatic',
  'stress',
  'disorder',
  'age',
  'still',
  'react',
  'anything',
  'sound',
  'like',
  'gunfire',
  'spent',
  'year',
  'working',
  'government',
  'army',
  'rest',
  'law',
  'enforcement',
  'found',
  'issue',
  'deal',
  'country',
  'lose',
  'prescription',
  'backpacking',
  'horrible',
  'two',
  'friend',
  'take',
  'pill',
  'evening',
  'bed',
  'side',
  'effect',
  'found',
  'zoloft',
  'god',
  'send'],
 ['anxiety',
  'make',
  'impossible',
  'situation',
  'possible',
  'control',
  'violence',
  'rage',
  'temper',
  'anger',
  'towards',
  'others',
  'post',
  'traumatic',
  'stress',
  'disorder',
  'panic',
  'attack',
  'keep',
  'calm',
  'best'],
 ['anxiety',
  'miracle',
  'put',
  'germany',
  'go',
  'insurance',
  'suffer',
  'depression',
  'anxiety',
  'often',
  'would',
  'find',
  'stuck',
  'daydream',
  'world',
  'thing',
  'going',
  'life',
  'including',
  'partner',
  'year',
  'would',
  'energy',
  'feel',
  'low',
  'finally',
  'insurance',
  'put',
  'mg',
  'day',
  'feel',
  'much',
  'better',
  'feel',
  'like',
  'handle',
  'life',
  'set',
  'goal',
  'dont',
  'feel',
  'anxiety',
  'dont',
  'sit',
  'think',
  'negative',
  'focus',
  'positive',
  'life',
  'fun',
  'interactive',
  'son',
  'literately',
  'saved',
  'life',
  'dont',
  'know'],
 ['pain',
  'fast',
  'acting',
  'chronic',
  'pain',
  'downside',
  'shorter',
  'time',
  'period',
  'relief',
  'pain',
  'medication'],
 ['anxiety',
  'prescribed',
  'via',
  'psychiatrist',
  'severe',
  'panic',
  'attack',
  'year',
  'take',
  'dosage',
  'late',
  'forget',
  'take',
  'withdrawal',
  'symptom',
  'kick',
  'gnawing',
  'physical',
  'pain',
  'breathlessness',
  'disorientation',
  'time',
  'difficulty',
  'word',
  'finding',
  'speaking',
  'severe',
  'muscle',
  'pain',
  'stiffness',
  'nausea',
  'labile',
  'emotion',
  'panic'],
 ['pain',
  'excruciating',
  'lower',
  'back',
  'pain',
  'along',
  'sciatica',
  'shot',
  'hip',
  'hr',
  'ago',
  'pain',
  'almost',
  'gone',
  'still',
  'little',
  'sciatica',
  'take',
  'day',
  'heal',
  'dr',
  'also',
  'prescribed',
  'vicodin',
  'dont',
  'think',
  'need',
  'tonight',
  'could',
  'barely',
  'walk',
  'dr',
  'visit',
  'much',
  'better',
  'drug',
  'work',
  'everyone',
  'worth',
  'try',
  'hope',
  'feel',
  'better'],
 ['anxiety',
  'bad',
  'doctor',
  'freaked',
  'addictive',
  'behavior',
  'point',
  'willing',
  'let',
  'people',
  'suffer',
  'valium',
  'low',
  'dose',
  'work',
  'junk',
  'may',
  'work',
  'even',
  'result',
  'using',
  'test',
  'rat',
  'seen',
  'state',
  'low',
  'result',
  'resent',
  'person',
  'really',
  'need',
  'help',
  'acute',
  'condition',
  'given',
  'kind',
  'low',
  'performing',
  'medication'],
 ['pain',
  'left',
  'eye',
  'destroyed',
  'broomstick',
  'fight',
  'doctor',
  'gave',
  'percocet',
  'joke',
  'still',
  'agony',
  'opana',
  'er',
  'trick'],
 ['depression',
  'medication',
  'far',
  'worst',
  'antidepressant',
  'taken',
  'first',
  'month',
  'seemed',
  'well',
  'year',
  'hit',
  'rock',
  'bottom',
  'mentally',
  'caused',
  'terrible',
  'symptom',
  'beneficial',
  'weird',
  'brain',
  'zap',
  'left',
  'bed',
  'day',
  'sleep',
  'disturbance',
  'attention',
  'seeking',
  'behavior',
  'well',
  'ocd',
  'never',
  'experienced',
  'previously',
  'took',
  'forever',
  'get',
  'terrible',
  'drug',
  'call',
  'terrible',
  'drug',
  'brain',
  'body',
  'get',
  'physically',
  'addicted',
  'way',
  'street',
  'drug',
  'would',
  'miss',
  'day',
  'start',
  'severe',
  'withdrawal',
  'sweat',
  'extreme',
  'brain',
  'zap',
  'feeling',
  'touch',
  'wrealitystrange',
  'thought',
  'month',
  'effexor',
  'bad',
  'stuff',
  'stopped'],
 ['pain',
  'whenever',
  'pain',
  'go',
  'medication',
  'back',
  'shoulder',
  'neck',
  'foot',
  'injury',
  'right',
  'medicine',
  'chronic',
  'pain',
  'right',
  'take',
  'rarely',
  'work',
  'needed',
  'avoid',
  'tolerance',
  'working',
  'able',
  'deal',
  'pain',
  'however',
  'go',
  'back',
  'work',
  'likely',
  'go',
  'medication',
  'similar',
  'one',
  'full',
  'time',
  'thing',
  'like',
  'fact',
  'many',
  'narcotic',
  'pain',
  'medication',
  'contain',
  'tylenol',
  'asperin',
  'ibuprofin',
  'make',
  'kidney',
  'liver',
  'organ',
  'go',
  'unnecessary',
  'stress',
  'prefer',
  'oxycodone',
  'need',
  'synergy',
  'tylenol',
  'add'],
 ['pain',
  'life',
  'livable',
  'side',
  'effect',
  'stay',
  'aware',
  'possibility',
  'abuse',
  'careful',
  'count',
  'pill',
  'throughout',
  'month',
  'give',
  'urine',
  'sample',
  'every',
  'couple',
  'month',
  'pain',
  'clinic',
  'dose',
  'mg',
  'every',
  'hour',
  'approx',
  'year',
  'go',
  'back',
  'life',
  'placed',
  'medicine',
  'always',
  'people',
  'abuse',
  'pain',
  'medicine',
  'understand',
  'doctor',
  'afraid',
  'prescribe',
  'someone',
  'stand',
  'treat',
  'people',
  'like',
  'get',
  'bed',
  'face',
  'day'],
 ['depression',
  'heart',
  'attack',
  'became',
  'depressed',
  'lexapro',
  'zoloft',
  'xanax',
  'ativan',
  'wellbutrin',
  'buspar',
  'none',
  'worked',
  'attempted',
  'suicide',
  'major',
  'depession',
  'anxiety',
  'disorder',
  'take',
  'comment',

In [49]:
"""
['depression','taken',-----,'year','improvement'] ---> 'antidepressant'
['taken','antidepressant',-----,'improvement','mostly'] -->'year'

 'mostly',
 'moderate',
 'severe',
 'side',
 'affect',
 'make',
 'go',


"""

"\n['depression','taken',-----,'year','improvement'] ---> 'antidepressant'\n['taken','antidepressant',-----,'improvement','mostly'] -->'year'\n\n 'mostly',\n 'moderate',\n 'severe',\n 'side',\n 'affect',\n 'make',\n 'go',\n\n\n"

In [50]:
df.head()

,review,label,clean_review,token
0,"Depression: ""I have taken anti-depressants for...",1,depression taken antidepressant year improveme...,"[depression, taken, antidepressant, year, impr..."
1,"Pain: ""I am 30 years old. I had a multiple com...",1,pain year old multiple composite spinal injury...,"[pain, year, old, multiple, composite, spinal,..."
2,"Pain: ""I love my Butrans patch!!! And it has r...",1,pain love butrans patch relieved half pain kno...,"[pain, love, butrans, patch, relieved, half, p..."
3,"Depression: ""This medicine saved my life. I wa...",1,depression medicine saved life wit end antidep...,"[depression, medicine, saved, life, wit, end, ..."
4,"Anxiety: ""I have been suffering with this anxi...",1,anxiety suffering anxiety problem year startin...,"[anxiety, suffering, anxiety, problem, year, s..."

In [52]:
from gensim.models import Word2Vec
sentence = df['token'].tolist()

w2v_model = Word2Vec( sentences=sentence,
         vector_size=100,
          window=5,
          min_count=2)

In [63]:
len(w2v_model.wv)

10260

In [54]:
w2v_model.wv.index_to_key[:20]

['pain',
 'anxiety',
 'depression',
 'mg',
 'day',
 'year',
 'take',
 'life',
 'effect',
 'feel',
 'taking',
 'medication',
 'side',
 'time',
 'work',
 'like',
 'week',
 'medicine',
 'doctor',
 'im']

In [55]:
w2v_model.wv['pain']

array([-0.46804982,  1.4714669 , -0.6827325 ,  0.59584624, -1.5582068 ,
       -1.16019   ,  0.6526675 ,  2.3732831 , -2.1805844 , -0.21106546,
        1.2391648 , -1.2771246 ,  0.17882425,  1.1965213 ,  0.8174656 ,
       -0.59096533,  0.4068287 ,  0.5437163 , -0.7298623 , -2.1697707 ,
        1.541121  ,  0.9389518 ,  1.1101661 ,  0.49976373,  1.1833514 ,
       -1.1350919 ,  0.82965577,  0.6615958 , -1.0938464 , -0.37189808,
        0.5650033 ,  0.9639466 ,  0.4202823 , -1.4134436 , -0.19959958,
       -1.0134437 ,  0.8834677 , -0.86349285,  1.0259852 , -0.05525068,
       -0.6262851 ,  1.0965877 , -0.8918056 , -0.73171496,  0.48814666,
        0.74023205, -0.06681377,  1.2490171 ,  0.6008234 ,  0.95473725,
       -1.1946418 ,  0.65804905, -0.6890875 , -0.45336163,  0.40356547,
       -0.47425428,  0.8941199 , -1.0489237 , -1.5654886 ,  0.89458734,
        0.30618355,  1.8987184 , -1.3432271 , -1.9835273 , -1.0772158 ,
        1.1188523 , -0.28703538,  0.734402  , -0.30907872, -1.3330117 ,
        0.58755344,  0.29502302,  0.6330025 , -1.251499  , -0.01763457,
        0.15095158,  1.0479023 , -0.06403869,  0.07715283, -1.0451075 ,
        0.90412146,  0.07299061,  1.8165962 , -0.49424648,  0.37560543,
        0.28667557,  1.0749208 , -0.7202942 ,  0.09038915, -0.48957258,
        0.6958677 ,  0.31444308,  0.4493667 , -0.09735698,  2.421559  ,
        0.9872844 , -0.33630335, -1.8597801 , -0.7085286 ,  1.0319338 ],
      dtype=float32)

In [65]:
w2v_model.wv.most_similar('vicodin')

[('percocet', 0.9698012471199036),
 ('morphine', 0.967583417892456),
 ('hydrocodone', 0.9657936692237854),
 ('tylenol', 0.9605554342269897),
 ('norco', 0.9569525718688965),
 ('demerol', 0.9528790712356567),
 ('ibuprofen', 0.9434986114501953),
 ('methadone', 0.9396712183952332),
 ('dilaudid', 0.9387991428375244),
 ('ultram', 0.9358431696891785)]

In [57]:
df.head()

,review,label,clean_review,token
0,"Depression: ""I have taken anti-depressants for...",1,depression taken antidepressant year improveme...,"[depression, taken, antidepressant, year, impr..."
1,"Pain: ""I am 30 years old. I had a multiple com...",1,pain year old multiple composite spinal injury...,"[pain, year, old, multiple, composite, spinal,..."
2,"Pain: ""I love my Butrans patch!!! And it has r...",1,pain love butrans patch relieved half pain kno...,"[pain, love, butrans, patch, relieved, half, p..."
3,"Depression: ""This medicine saved my life. I wa...",1,depression medicine saved life wit end antidep...,"[depression, medicine, saved, life, wit, end, ..."
4,"Anxiety: ""I have been suffering with this anxi...",1,anxiety suffering anxiety problem year startin...,"[anxiety, suffering, anxiety, problem, year, s..."

In [58]:
"depression" in w2v_model.wv

True

In [69]:
w2v_model.wv["depression"]

array([-0.6372835 , -0.20229632, -1.862474  ,  0.87764907,  1.8174483 ,
       -0.5488038 ,  0.42513183,  1.4132004 , -0.55472976,  0.21267691,
       -0.40558168, -0.9849243 , -0.78520197, -1.5513203 ,  0.18291204,
        0.34713617,  0.3414187 ,  0.77581465, -0.2834906 , -2.1088798 ,
       -0.18662517,  0.54377025,  0.3865483 , -0.91864645,  0.7323071 ,
       -0.02805413, -0.14136468, -0.43778875, -0.21574174,  0.8615975 ,
       -0.37899545, -1.1477157 ,  0.03490561, -1.1667068 ,  0.37459487,
        1.6741354 , -0.31199935,  0.12735094, -0.513656  ,  0.15525918,
        0.629726  , -0.5239805 , -0.81578314, -0.611244  , -0.44123012,
       -0.24766235, -0.581742  ,  0.38866535,  0.37182683,  0.14374645,
        1.1891717 , -1.8073223 ,  1.3986484 ,  0.18299262, -1.7593305 ,
        0.5706903 ,  1.4026814 ,  0.56846046,  0.09897868,  0.6357893 ,
       -0.38869345, -0.45762107,  1.0072535 , -1.0429589 , -0.82410425,
        1.8916752 ,  0.48844033,  1.441777  , -0.9100386 ,  1.5956463 ,
       -0.60769904,  0.01892681,  0.10829294,  0.46135   ,  0.7784204 ,
       -0.49815893,  0.5771055 ,  0.54413545, -0.18184263, -0.09267539,
       -1.706963  ,  0.61154944, -0.68013096,  0.4874013 , -1.0378644 ,
       -0.61635846,  0.38954374,  0.4769373 ,  0.3885741 ,  0.04460092,
       -0.08751025, -0.16887534,  0.18817542,  0.70382434,  1.1557844 ,
        0.9826181 ,  0.56339014, -0.9122059 ,  0.78742296,  0.58969694],
      dtype=float32)

In [68]:
w2v_model.wv["thougts"]

KeyError: "Key 'thougts' not present"

In [76]:
df.head(2)

,review,label,clean_review,token
0,"Depression: ""I have taken anti-depressants for...",1,depression taken antidepressant year improveme...,"[depression, taken, antidepressant, year, impr..."
1,"Pain: ""I am 30 years old. I had a multiple com...",1,pain year old multiple composite spinal injury...,"[pain, year, old, multiple, composite, spinal,..."

In [67]:
# token == [[100],[100],[100],[100]] -->[[100]]
# [[100]]

import numpy as np

def document_vector(tokens):
  doc_vector = []
  for token in tokens:
    if token in w2v_model.wv:
      doc_vector.append(w2v_model.wv[token])
    else:
      print(f"the word is missing from the WV object : {token}")
      doc_vector.append(np.zeros(100))
  if len(doc_vector) == 0:
    return np.zeros(100)

  return np.mean(doc_vector,axis=0)

the word is missing from the WV object : musicianspublic
the word is missing from the WV object : speaker
the word is missing from the WV object : embarrass
the word is missing from the WV object : mastectomy
the word is missing from the WV object : thisthank
the word is missing from the WV object : sssnris
the word is missing from the WV object : wheezy
the word is missing from the WV object : eradicated
the word is missing from the WV object : watcher
the word is missing from the WV object : daydream
the word is missing from the WV object : literately
the word is missing from the WV object : batttling
the word is missing from the WV object : persevering
the word is missing from the WV object : mitigating
the word is missing from the WV object : assertive
the word is missing from the WV object : coldturkey
the word is missing from the WV object : panicshakedepression
the word is missing from the WV object : jointsbig
the word is missing from the WV object : bodily
the word is missing from the WV object : sbout
the word is missing from the WV object : sideways
the word is missing from the WV object : dysfunctionpots
the word is missing from the WV object : bossy
the word is missing from the WV object : uncontrallably
the word is missing from the WV object : arnt
the word is missing from the WV object : eczema
the word is missing from the WV object : canadian
the word is missing from the WV object : alls
the word is missing from the WV object : basement
the word is missing from the WV object : voiceso
the word is missing from the WV object : hypermobility
the word is missing from the WV object : agitationirritability
the word is missing from the WV object : hormonally
the word is missing from the WV object : attackssince
the word is missing from the WV object : hydroxyzineim
the word is missing from the WV object : moodstill
the word is missing from the WV object : boosted
the word is missing from the WV object : clonopinfeeling
the word is missing from the WV object : workwhat
the word is missing from the WV object : atenenol
the word is missing from the WV object : atenol
the word is missing from the WV object : indicating
the word is missing from the WV object : neropathy
the word is missing from the WV object : thani
the word is missing from the WV object : fart
the word is missing from the WV object : eveninghelps
the word is missing from the WV object : lastsleep
the word is missing from the WV object : arrow
the word is missing from the WV object : frazzled
the word is missing from the WV object : lumbarsacral
the word is missing from the WV object : codonehead
the word is missing from the WV object : risperdone
the word is missing from the WV object : lifemy
the word is missing from the WV object : visionary
the word is missing from the WV object : congestion
the word is missing from the WV object : livid
the word is missing from the WV object : parentjust
the word is missing from the WV object : imparing
the word is missing from the WV object : mississippi
the word is missing from the WV object : ordering
the word is missing from the WV object : drv
the word is missing from the WV object : delay
the word is missing from the WV object : valiumis
the word is missing from the WV object : ambian
the word is missing from the WV object : yup
the word is missing from the WV object : consecutive
the word is missing from the WV object : atavan
the word is missing from the WV object : joanzie
the word is missing from the WV object : norpramin
the word is missing from the WV object : lgm
the word is missing from the WV object : lala
the word is missing from the WV object : eddie
the word is missing from the WV object : polyethylene
the word is missing from the WV object : glycol
the word is missing from the WV object : malox
the word is missing from the WV object : alpha
the word is missing from the WV object : antitrypsin
the word is missing from the WV object : furthermore
the word is missing from the WV object : barbiturate
the word is missing from the WV object : medrol
the word is missing from the WV object : trainer
the word is missing from the WV object : radiculitus
the word is missing from the WV object : alters
the word is missing from the WV object : laterfelt
the word is missing from the WV object : halfand
the word is missing from the WV object : abuseaddiction
the word is missing from the WV object : offandon
the word is missing from the WV object : dodgy
the word is missing from the WV object : dayone
the word is missing from the WV object : anklefoot
the word is missing from the WV object : akin
the word is missing from the WV object : hourly
the word is missing from the WV object : ventured
the word is missing from the WV object : bioidentical
the word is missing from the WV object : benzoyl
the word is missing from the WV object : peroxide
the word is missing from the WV object : pulsesshocks
the word is missing from the WV object : worthlessdoctor
the word is missing from the WV object : amputated
the word is missing from the WV object : quotextendquot
the word is missing from the WV object : truvada
the word is missing from the WV object : isentress
the word is missing from the WV object : openminded
the word is missing from the WV object : queen
the word is missing from the WV object : skewed
the word is missing from the WV object : dyndrome
the word is missing from the WV object : comforted
the word is missing from the WV object : dizzyspells
the word is missing from the WV object : quothypochondriaquot
the word is missing from the WV object : daycrying
the word is missing from the WV object : quotnot
the word is missing from the WV object : therequot
the word is missing from the WV object : gabapintin
the word is missing from the WV object : soothing
the word is missing from the WV object : potty
the word is missing from the WV object : goodif
the word is missing from the WV object : gratefuldont
the word is missing from the WV object : endlessly
the word is missing from the WV object : daysweeks
the word is missing from the WV object : illogical
the word is missing from the WV object : diclofence
the word is missing from the WV object : partying
the word is missing from the WV object : dancing
the word is missing from the WV object : clothing
the word is missing from the WV object : burnt
the word is missing from the WV object : rearly
the word is missing from the WV object : schoolstopped
the word is missing from the WV object : eatingstopped
the word is missing from the WV object : repairable
the word is missing from the WV object : societal
the word is missing from the WV object : presenting
the word is missing from the WV object : tryclicerides
the word is missing from the WV object : tca
the word is missing from the WV object : sertilne
the word is missing from the WV object : cornerstone
the word is missing from the WV object : levo
the word is missing from the WV object : crowding
the word is missing from the WV object : sub
the word is missing from the WV object : nursei
the word is missing from the WV object : dihydrocodeine
the word is missing from the WV object : unfortunatly
the word is missing from the WV object : prey
the word is missing from the WV object : disappointment
the word is missing from the WV object : enforcing
the word is missing from the WV object : practionair
the word is missing from the WV object : shyed
the word is missing from the WV object : accepts
the word is missing from the WV object : quackes
the word is missing from the WV object : suppliment
the word is missing from the WV object : foresee
the word is missing from the WV object : pericarditis
the word is missing from the WV object : lacerated
the word is missing from the WV object : mba
the word is missing from the WV object : physic
the word is missing from the WV object : capsulitis
the word is missing from the WV object : trolamine
the word is missing from the WV object : salicylate
the word is missing from the WV object : leastmildest
the word is missing from the WV object : deltoid
the word is missing from the WV object : quotwhoa
the word is missing from the WV object : dangerousquot
the word is missing from the WV object : discern
the word is missing from the WV object : ssrisquot
the word is missing from the WV object : generation
the word is missing from the WV object : antdepressants
the word is missing from the WV object : monthsinitially
the word is missing from the WV object : impinged
the word is missing from the WV object : solpadol
the word is missing from the WV object : upright
the word is missing from the WV object : vibryd
the word is missing from the WV object : acetominophen
the word is missing from the WV object : biggie
the word is missing from the WV object : quickacting
the word is missing from the WV object : wagon
the word is missing from the WV object : extremeties
the word is missing from the WV object : devastation
the word is missing from the WV object : melanoma
the word is missing from the WV object : vicodinvicoprofenlortab
the word is missing from the WV object : quotzoned
the word is missing from the WV object : cincinnati
the word is missing from the WV object : generate
the word is missing from the WV object : himher
the word is missing from the WV object : uncommon
the word is missing from the WV object : idio
the word is missing from the WV object : pathic
the word is missing from the WV object : begining
the word is missing from the WV object : lesion
the word is missing from the WV object : quotcalmquot
the word is missing from the WV object : stylist
the word is missing from the WV object : goergous
the word is missing from the WV object : womenyes
the word is missing from the WV object : straighthowever
the word is missing from the WV object : miami
the word is missing from the WV object : galveston
the word is missing from the WV object : texas
the word is missing from the WV object : accordance
the word is missing from the WV object : obstacle
the word is missing from the WV object : gourmet
the word is missing from the WV object : lifestylemaybe
the word is missing from the WV object : unabating
the word is missing from the WV object : quotwhats
the word is missing from the WV object : nextquot
the word is missing from the WV object : deadquot
the word is missing from the WV object : fianceacute
the word is missing from the WV object : numbess
the word is missing from the WV object : alprazolammg
the word is missing from the WV object : regaining
the word is missing from the WV object : quotemergencies
the word is missing from the WV object : onlyquot
the word is missing from the WV object : quotevenquot
the word is missing from the WV object : string
the word is missing from the WV object : huntsville
the word is missing from the WV object : lake
the word is missing from the WV object : utah
the word is missing from the WV object : satiably
the word is missing from the WV object : equaled
the word is missing from the WV object : quotmodernquot
the word is missing from the WV object : quotmaintenancequot
the word is missing from the WV object : activei
the word is missing from the WV object : mustcbe
the word is missing from the WV object : hourstapered
the word is missing from the WV object : hellhearing
the word is missing from the WV object : voicesvertigo
the word is missing from the WV object : nauseavomitingcrying
the word is missing from the WV object : maniasevere
the word is missing from the WV object : confusionmemory
the word is missing from the WV object : losssweating
the word is missing from the WV object : craptaking
the word is missing from the WV object : symptomsterrified
the word is missing from the WV object : stunted
the word is missing from the WV object : yah
the word is missing from the WV object : overthecounter
the word is missing from the WV object : bestresponding
the word is missing from the WV object : ge
the word is missing from the WV object : adversely
the word is missing from the WV object : cocoon
the word is missing from the WV object : unive
the word is missing from the WV object : pillar
the word is missing from the WV object : sleepwake
the word is missing from the WV object : wantedneeded
the word is missing from the WV object : miniscus
the word is missing from the WV object : anaesthesia
the word is missing from the WV object : relieverquot
the word is missing from the WV object : etcin
the word is missing from the WV object : quotevents
the word is missing from the WV object : waist
the word is missing from the WV object : vicodins
the word is missing from the WV object : draino
the word is missing from the WV object : conundrumbottom
the word is missing from the WV object : hypersalivation
the word is missing from the WV object : aniextydepression
the word is missing from the WV object : alprazol
the word is missing from the WV object : anixety
the word is missing from the WV object : workday
the word is missing from the WV object : endometrosis
the word is missing from the WV object : cual
the word is missing from the WV object : underground
the word is missing from the WV object : sand
the word is missing from the WV object : fruitful
the word is missing from the WV object : liter
the word is missing from the WV object : qeeg
the word is missing from the WV object : quotfast
the word is missing from the WV object : brainquot
the word is missing from the WV object : hyperarousal
the word is missing from the WV object : arounddepression
the word is missing from the WV object : familymostly
the word is missing from the WV object : untreatedi
the word is missing from the WV object : lifebut
the word is missing from the WV object : functioningif
the word is missing from the WV object : insidein
the word is missing from the WV object : deeplyterribly
the word is missing from the WV object : sadstresseddepressedhopelessand
the word is missing from the WV object : disordersad
the word is missing from the WV object : fluoroxetine
the word is missing from the WV object : balancedhappycontent
the word is missing from the WV object : positivenot
the word is missing from the WV object : alli
the word is missing from the WV object : circulation
the word is missing from the WV object : neuoprathy
the word is missing from the WV object : sittingstanding
the word is missing from the WV object : inconsequential
the word is missing from the WV object : playng
the word is missing from the WV object : whatif
the word is missing from the WV object : pcos
the word is missing from the WV object : weightrelated
the word is missing from the WV object : torso
the word is missing from the WV object : physian
the word is missing from the WV object : deprive
the word is missing from the WV object : shun
the word is missing from the WV object : astonishingly
the word is missing from the WV object : notsohealthy
the word is missing from the WV object : subutexbuprenorphine
the word is missing from the WV object : stupor
the word is missing from the WV object : neglecting
the word is missing from the WV object : blackout
the word is missing from the WV object : mending
the word is missing from the WV object : drugit
the word is missing from the WV object : persuading
the word is missing from the WV object : ldquonormalrdquo
the word is missing from the WV object : disables
the word is missing from the WV object : antidepressantsnone
the word is missing from the WV object : tradition
the word is missing from the WV object : lorazepram
the word is missing from the WV object : flavor
the word is missing from the WV object : grass
the word is missing from the WV object : freshness
the word is missing from the WV object : overblown
the word is missing from the WV object : friendrelative
the word is missing from the WV object : selfeducate
the word is missing from the WV object : pusher
the word is missing from the WV object : basisquot
the word is missing from the WV object : arises
the word is missing from the WV object : ihave
the word is missing from the WV object : benzodiaphines
the word is missing from the WV object : metamorphosis
the word is missing from the WV object : informing
the word is missing from the WV object : selegiline
the word is missing from the WV object : observe
the word is missing from the WV object : dhea
the word is missing from the WV object : fental
the word is missing from the WV object : staph
the word is missing from the WV object : yeast
the word is missing from the WV object : zinger
the word is missing from the WV object : fogfeeling
the word is missing from the WV object : admission
the word is missing from the WV object : hyperhidrosis
the word is missing from the WV object : tended
the word is missing from the WV object : underarm
the word is missing from the WV object : irregularly
the word is missing from the WV object : submitted
the word is missing from the WV object : abilfyand
the word is missing from the WV object : restlessly
the word is missing from the WV object : volunteered
the word is missing from the WV object : spazms
the word is missing from the WV object : generalzed
the word is missing from the WV object : clumsiness
the word is missing from the WV object : docsb
the word is missing from the WV object : pointless
the word is missing from the WV object : thismy
the word is missing from the WV object : pn
the word is missing from the WV object : quotidiotsquot
the word is missing from the WV object : decreasingand
the word is missing from the WV object : grrrreat
the word is missing from the WV object : paroxsymal
the word is missing from the WV object : hemicrania
the word is missing from the WV object : glucose
the word is missing from the WV object : nondiabetic
the word is missing from the WV object : belching
the word is missing from the WV object : miserbaly
the word is missing from the WV object : propananol
the word is missing from the WV object : helpeduntil
the word is missing from the WV object : disassociative
the word is missing from the WV object : sucide
the word is missing from the WV object : flame
the word is missing from the WV object : delivering
the word is missing from the WV object : flexaril
the word is missing from the WV object : biopsy
the word is missing from the WV object : ibuprofenacetaminophennaproxenir
the word is missing from the WV object : pnd
the word is missing from the WV object : slurring
the word is missing from the WV object : binging
the word is missing from the WV object : sigh
the word is missing from the WV object : humane
the word is missing from the WV object : bearing
the word is missing from the WV object : dredging
the word is missing from the WV object : quotserotonin
the word is missing from the WV object : modulator
the word is missing from the WV object : stimulatorquot
the word is missing from the WV object : ht
the word is missing from the WV object : rumbling
the word is missing from the WV object : tracer
the word is missing from the WV object : yrsyou
the word is missing from the WV object : quotmayquot
the word is missing from the WV object : toredol
the word is missing from the WV object : esteemed
the word is missing from the WV object : greaaattt
the word is missing from the WV object : dissappearance
the word is missing from the WV object : hydrocodoneday
the word is missing from the WV object : hydros
the word is missing from the WV object : plo
the word is missing from the WV object : amytriptiline
the word is missing from the WV object : wth
the word is missing from the WV object : drawn
the word is missing from the WV object : humira
the word is missing from the WV object : plaquenil
the word is missing from the WV object : fixing
the word is missing from the WV object : terrorism
the word is missing from the WV object : busiprone
the word is missing from the WV object : carcinoma
the word is missing from the WV object : sisterinlaw
the word is missing from the WV object : peel

In [70]:
X = df["token"].apply(document_vector).tolist()

the word is missing from the WV object : musicianspublic
the word is missing from the WV object : speaker
the word is missing from the WV object : embarrass
the word is missing from the WV object : mastectomy
the word is missing from the WV object : thisthank
the word is missing from the WV object : sssnris
the word is missing from the WV object : wheezy
the word is missing from the WV object : eradicated
the word is missing from the WV object : watcher
the word is missing from the WV object : daydream
the word is missing from the WV object : literately
the word is missing from the WV object : batttling
the word is missing from the WV object : persevering
the word is missing from the WV object : mitigating
the word is missing from the WV object : assertive
the word is missing from the WV object : coldturkey
the word is missing from the WV object : panicshakedepression
the word is missing from the WV object : jointsbig
the word is missing from the WV object : bodily
the word is missing from the WV object : sbout
the word is missing from the WV object : sideways
the word is missing from the WV object : dysfunctionpots
the word is missing from the WV object : bossy
the word is missing from the WV object : uncontrallably
the word is missing from the WV object : arnt
the word is missing from the WV object : eczema
the word is missing from the WV object : canadian
the word is missing from the WV object : alls
the word is missing from the WV object : basement
the word is missing from the WV object : voiceso
the word is missing from the WV object : hypermobility
the word is missing from the WV object : agitationirritability
the word is missing from the WV object : hormonally
the word is missing from the WV object : attackssince
the word is missing from the WV object : hydroxyzineim
the word is missing from the WV object : moodstill
the word is missing from the WV object : boosted
the word is missing from the WV object : clonopinfeeling
the word is missing from the WV object : workwhat
the word is missing from the WV object : atenenol
the word is missing from the WV object : atenol
the word is missing from the WV object : indicating
the word is missing from the WV object : neropathy
the word is missing from the WV object : thani
the word is missing from the WV object : fart
the word is missing from the WV object : eveninghelps
the word is missing from the WV object : lastsleep
the word is missing from the WV object : arrow
the word is missing from the WV object : frazzled
the word is missing from the WV object : lumbarsacral
the word is missing from the WV object : codonehead
the word is missing from the WV object : risperdone
the word is missing from the WV object : lifemy
the word is missing from the WV object : visionary
the word is missing from the WV object : congestion
the word is missing from the WV object : livid
the word is missing from the WV object : parentjust
the word is missing from the WV object : imparing
the word is missing from the WV object : mississippi
the word is missing from the WV object : ordering
the word is missing from the WV object : drv
the word is missing from the WV object : delay
the word is missing from the WV object : valiumis
the word is missing from the WV object : ambian
the word is missing from the WV object : yup
the word is missing from the WV object : consecutive
the word is missing from the WV object : atavan
the word is missing from the WV object : joanzie
the word is missing from the WV object : norpramin
the word is missing from the WV object : lgm
the word is missing from the WV object : lala
the word is missing from the WV object : eddie
the word is missing from the WV object : polyethylene
the word is missing from the WV object : glycol
the word is missing from the WV object : malox
the word is missing from the WV object : alpha
the word is missing from the WV object : antitrypsin
the word is missing from the WV object : furthermore
the word is missing from the WV object : barbiturate
the word is missing from the WV object : medrol
the word is missing from the WV object : trainer
the word is missing from the WV object : radiculitus
the word is missing from the WV object : alters
the word is missing from the WV object : laterfelt
the word is missing from the WV object : halfand
the word is missing from the WV object : abuseaddiction
the word is missing from the WV object : offandon
the word is missing from the WV object : dodgy
the word is missing from the WV object : dayone
the word is missing from the WV object : anklefoot
the word is missing from the WV object : akin
the word is missing from the WV object : hourly
the word is missing from the WV object : ventured
the word is missing from the WV object : bioidentical
the word is missing from the WV object : benzoyl
the word is missing from the WV object : peroxide
the word is missing from the WV object : pulsesshocks
the word is missing from the WV object : worthlessdoctor
the word is missing from the WV object : amputated
the word is missing from the WV object : quotextendquot
the word is missing from the WV object : truvada
the word is missing from the WV object : isentress
the word is missing from the WV object : openminded
the word is missing from the WV object : queen
the word is missing from the WV object : skewed
the word is missing from the WV object : dyndrome
the word is missing from the WV object : comforted
the word is missing from the WV object : dizzyspells
the word is missing from the WV object : quothypochondriaquot
the word is missing from the WV object : daycrying
the word is missing from the WV object : quotnot
the word is missing from the WV object : therequot
the word is missing from the WV object : gabapintin
the word is missing from the WV object : soothing
the word is missing from the WV object : potty
the word is missing from the WV object : goodif
the word is missing from the WV object : gratefuldont
the word is missing from the WV object : endlessly
the word is missing from the WV object : daysweeks
the word is missing from the WV object : illogical
the word is missing from the WV object : diclofence
the word is missing from the WV object : partying
the word is missing from the WV object : dancing
the word is missing from the WV object : clothing
the word is missing from the WV object : burnt
the word is missing from the WV object : rearly
the word is missing from the WV object : schoolstopped
the word is missing from the WV object : eatingstopped
the word is missing from the WV object : repairable
the word is missing from the WV object : societal
the word is missing from the WV object : presenting
the word is missing from the WV object : tryclicerides
the word is missing from the WV object : tca
the word is missing from the WV object : sertilne
the word is missing from the WV object : cornerstone
the word is missing from the WV object : levo
the word is missing from the WV object : crowding
the word is missing from the WV object : sub
the word is missing from the WV object : nursei
the word is missing from the WV object : dihydrocodeine
the word is missing from the WV object : unfortunatly
the word is missing from the WV object : prey
the word is missing from the WV object : disappointment
the word is missing from the WV object : enforcing
the word is missing from the WV object : practionair
the word is missing from the WV object : shyed
the word is missing from the WV object : accepts
the word is missing from the WV object : quackes
the word is missing from the WV object : suppliment
the word is missing from the WV object : foresee
the word is missing from the WV object : pericarditis
the word is missing from the WV object : lacerated
the word is missing from the WV object : mba
the word is missing from the WV object : physic
the word is missing from the WV object : capsulitis
the word is missing from the WV object : trolamine
the word is missing from the WV object : salicylate
the word is missing from the WV object : leastmildest
the word is missing from the WV object : deltoid
the word is missing from the WV object : quotwhoa
the word is missing from the WV object : dangerousquot
the word is missing from the WV object : discern
the word is missing from the WV object : ssrisquot
the word is missing from the WV object : generation
the word is missing from the WV object : antdepressants
the word is missing from the WV object : monthsinitially
the word is missing from the WV object : impinged
the word is missing from the WV object : solpadol
the word is missing from the WV object : upright
the word is missing from the WV object : vibryd
the word is missing from the WV object : acetominophen
the word is missing from the WV object : biggie
the word is missing from the WV object : quickacting
the word is missing from the WV object : wagon
the word is missing from the WV object : extremeties
the word is missing from the WV object : devastation
the word is missing from the WV object : melanoma
the word is missing from the WV object : vicodinvicoprofenlortab
the word is missing from the WV object : quotzoned
the word is missing from the WV object : cincinnati
the word is missing from the WV object : generate
the word is missing from the WV object : himher
the word is missing from the WV object : uncommon
the word is missing from the WV object : idio
the word is missing from the WV object : pathic
the word is missing from the WV object : begining
the word is missing from the WV object : lesion
the word is missing from the WV object : quotcalmquot
the word is missing from the WV object : stylist
the word is missing from the WV object : goergous
the word is missing from the WV object : womenyes
the word is missing from the WV object : straighthowever
the word is missing from the WV object : miami
the word is missing from the WV object : galveston
the word is missing from the WV object : texas
the word is missing from the WV object : accordance
the word is missing from the WV object : obstacle
the word is missing from the WV object : gourmet
the word is missing from the WV object : lifestylemaybe
the word is missing from the WV object : unabating
the word is missing from the WV object : quotwhats
the word is missing from the WV object : nextquot
the word is missing from the WV object : deadquot
the word is missing from the WV object : fianceacute
the word is missing from the WV object : numbess
the word is missing from the WV object : alprazolammg
the word is missing from the WV object : regaining
the word is missing from the WV object : quotemergencies
the word is missing from the WV object : onlyquot
the word is missing from the WV object : quotevenquot
the word is missing from the WV object : string
the word is missing from the WV object : huntsville
the word is missing from the WV object : lake
the word is missing from the WV object : utah
the word is missing from the WV object : satiably
the word is missing from the WV object : equaled
the word is missing from the WV object : quotmodernquot
the word is missing from the WV object : quotmaintenancequot
the word is missing from the WV object : activei
the word is missing from the WV object : mustcbe
the word is missing from the WV object : hourstapered
the word is missing from the WV object : hellhearing
the word is missing from the WV object : voicesvertigo
the word is missing from the WV object : nauseavomitingcrying
the word is missing from the WV object : maniasevere
the word is missing from the WV object : confusionmemory
the word is missing from the WV object : losssweating
the word is missing from the WV object : craptaking
the word is missing from the WV object : symptomsterrified
the word is missing from the WV object : stunted
the word is missing from the WV object : yah
the word is missing from the WV object : overthecounter
the word is missing from the WV object : bestresponding
the word is missing from the WV object : ge
the word is missing from the WV object : adversely
the word is missing from the WV object : cocoon
the word is missing from the WV object : unive
the word is missing from the WV object : pillar
the word is missing from the WV object : sleepwake
the word is missing from the WV object : wantedneeded
the word is missing from the WV object : miniscus
the word is missing from the WV object : anaesthesia
the word is missing from the WV object : relieverquot
the word is missing from the WV object : etcin
the word is missing from the WV object : quotevents
the word is missing from the WV object : waist
the word is missing from the WV object : vicodins
the word is missing from the WV object : draino
the word is missing from the WV object : conundrumbottom
the word is missing from the WV object : hypersalivation
the word is missing from the WV object : aniextydepression
the word is missing from the WV object : alprazol
the word is missing from the WV object : anixety
the word is missing from the WV object : workday
the word is missing from the WV object : endometrosis
the word is missing from the WV object : cual
the word is missing from the WV object : underground
the word is missing from the WV object : sand
the word is missing from the WV object : fruitful
the word is missing from the WV object : liter
the word is missing from the WV object : qeeg
the word is missing from the WV object : quotfast
the word is missing from the WV object : brainquot
the word is missing from the WV object : hyperarousal
the word is missing from the WV object : arounddepression
the word is missing from the WV object : familymostly
the word is missing from the WV object : untreatedi
the word is missing from the WV object : lifebut
the word is missing from the WV object : functioningif
the word is missing from the WV object : insidein
the word is missing from the WV object : deeplyterribly
the word is missing from the WV object : sadstresseddepressedhopelessand
the word is missing from the WV object : disordersad
the word is missing from the WV object : fluoroxetine
the word is missing from the WV object : balancedhappycontent
the word is missing from the WV object : positivenot
the word is missing from the WV object : alli
the word is missing from the WV object : circulation
the word is missing from the WV object : neuoprathy
the word is missing from the WV object : sittingstanding
the word is missing from the WV object : inconsequential
the word is missing from the WV object : playng
the word is missing from the WV object : whatif
the word is missing from the WV object : pcos
the word is missing from the WV object : weightrelated
the word is missing from the WV object : torso
the word is missing from the WV object : physian
the word is missing from the WV object : deprive
the word is missing from the WV object : shun
the word is missing from the WV object : astonishingly
the word is missing from the WV object : notsohealthy
the word is missing from the WV object : subutexbuprenorphine
the word is missing from the WV object : stupor
the word is missing from the WV object : neglecting
the word is missing from the WV object : blackout
the word is missing from the WV object : mending
the word is missing from the WV object : drugit
the word is missing from the WV object : persuading
the word is missing from the WV object : ldquonormalrdquo
the word is missing from the WV object : disables
the word is missing from the WV object : antidepressantsnone
the word is missing from the WV object : tradition
the word is missing from the WV object : lorazepram
the word is missing from the WV object : flavor
the word is missing from the WV object : grass
the word is missing from the WV object : freshness
the word is missing from the WV object : overblown
the word is missing from the WV object : friendrelative
the word is missing from the WV object : selfeducate
the word is missing from the WV object : pusher
the word is missing from the WV object : basisquot
the word is missing from the WV object : arises
the word is missing from the WV object : ihave
the word is missing from the WV object : benzodiaphines
the word is missing from the WV object : metamorphosis
the word is missing from the WV object : informing
the word is missing from the WV object : selegiline
the word is missing from the WV object : observe
the word is missing from the WV object : dhea
the word is missing from the WV object : fental
the word is missing from the WV object : staph
the word is missing from the WV object : yeast
the word is missing from the WV object : zinger
the word is missing from the WV object : fogfeeling
the word is missing from the WV object : admission
the word is missing from the WV object : hyperhidrosis
the word is missing from the WV object : tended
the word is missing from the WV object : underarm
the word is missing from the WV object : irregularly
the word is missing from the WV object : submitted
the word is missing from the WV object : abilfyand
the word is missing from the WV object : restlessly
the word is missing from the WV object : volunteered
the word is missing from the WV object : spazms
the word is missing from the WV object : generalzed
the word is missing from the WV object : clumsiness
the word is missing from the WV object : docsb
the word is missing from the WV object : pointless
the word is missing from the WV object : thismy
the word is missing from the WV object : pn
the word is missing from the WV object : quotidiotsquot
the word is missing from the WV object : decreasingand
the word is missing from the WV object : grrrreat
the word is missing from the WV object : paroxsymal
the word is missing from the WV object : hemicrania
the word is missing from the WV object : glucose
the word is missing from the WV object : nondiabetic
the word is missing from the WV object : belching
the word is missing from the WV object : miserbaly
the word is missing from the WV object : propananol
the word is missing from the WV object : helpeduntil
the word is missing from the WV object : disassociative
the word is missing from the WV object : sucide
the word is missing from the WV object : flame
the word is missing from the WV object : delivering
the word is missing from the WV object : flexaril
the word is missing from the WV object : biopsy
the word is missing from the WV object : ibuprofenacetaminophennaproxenir
the word is missing from the WV object : pnd
the word is missing from the WV object : slurring
the word is missing from the WV object : binging
the word is missing from the WV object : sigh
the word is missing from the WV object : humane
the word is missing from the WV object : bearing
the word is missing from the WV object : dredging
the word is missing from the WV object : quotserotonin
the word is missing from the WV object : modulator
the word is missing from the WV object : stimulatorquot
the word is missing from the WV object : ht
the word is missing from the WV object : rumbling
the word is missing from the WV object : tracer
the word is missing from the WV object : yrsyou
the word is missing from the WV object : quotmayquot
the word is missing from the WV object : toredol
the word is missing from the WV object : esteemed
the word is missing from the WV object : greaaattt
the word is missing from the WV object : dissappearance
the word is missing from the WV object : hydrocodoneday
the word is missing from the WV object : hydros
the word is missing from the WV object : plo
the word is missing from the WV object : amytriptiline
the word is missing from the WV object : wth
the word is missing from the WV object : drawn
the word is missing from the WV object : humira
the word is missing from the WV object : plaquenil
the word is missing from the WV object : fixing
the word is missing from the WV object : terrorism
the word is missing from the WV object : busiprone
the word is missing from the WV object : carcinoma
the word is missing from the WV object : sisterinlaw
the word is missing from the WV object : peel

In [75]:
X[2]

array([ 0.06761343,  0.6584801 ,  0.10646315, -0.17763628, -0.3671304 ,
       -0.55798405,  0.1595861 ,  1.2242261 , -0.91269344, -0.15903479,
        0.129491  , -0.79277337,  0.15243508,  0.57833815,  0.5131173 ,
       -0.39105618, -0.0790574 , -0.22991817, -0.07783547, -1.1103295 ,
        0.5327209 ,  0.396848  ,  0.4226634 ,  0.25831395, -0.17131433,
       -0.02491301, -0.13065428, -0.153004  , -0.38234213, -0.19467887,
        0.644633  ,  0.18092637,  0.21598902, -0.5290011 , -0.368779  ,
       -0.19674543,  0.31237856, -0.3063826 , -0.06507413, -0.4667561 ,
       -0.17187686, -0.13614054, -0.07161752,  0.10896169,  0.29707918,
        0.16628577, -0.2228298 , -0.12981857,  0.44105256,  0.23137107,
       -0.20008716,  0.03531716, -0.44727725, -0.27812696,  0.24442482,
       -0.37085173,  0.41415966, -0.42222384, -0.6115589 ,  0.34483507,
        0.10879739,  0.45981207, -0.49069923, -0.23723124, -0.416257  ,
        0.45890263,  0.10108116,  0.01405905, -0.40897015, -0.4636765 ,
       -0.26470572,  0.04292161,  0.3016896 , -0.3736851 ,  0.22601967,
        0.30098912,  0.08405302,  0.04501558, -0.24950267, -0.03958251,
        0.21597105,  0.1085012 , -0.01963367,  0.1372817 ,  0.08119744,
        0.07486145,  0.15241323,  0.4200357 ,  0.09766672, -0.19693083,
        0.6692817 ,  0.4637234 ,  0.05484376, -0.0562211 ,  0.97936356,
        0.0690455 ,  0.23715875, -0.47909087, -0.06225225,  0.1183923 ],
      dtype=float32)

In [78]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [79]:
# random forest

model = RandomForestClassifier()
model.fit(X_train,y_train)

y_pred = model.predict(X_test)

print('Test Accuracy:', accuracy_score(y_test, y_pred))

y_pred_train = model.predict(X_train)
print('Train Accuracy:', accuracy_score(y_train, y_pred_train))
#

Test Accuracy: 0.9405695418902187
Train Accuracy: 0.9995871606976984